name: Blue-Green Deployment

on:
  workflow_dispatch:
    inputs:
      lambda_function_name:
        description: "Lambda function to apply the deployment strategy to"
        type: string
        required: true
      prev_lambda_function_version:
        description: "Previous Lambda function version to update the alias"
        required: true
        type: string
      lambda_function_version:
        description: "Lambda function version to update the alias"
        required: true
        type: string
      weighted_traffic_percentage:
        description: "The weighted traffic amount (in decimal) to be updated with the deployment strategy"
        required: true
        type: string
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true
permissions:
  id-token: write
  contents: read
env:
  NODE_VERSION: "20.x"
jobs:
  selections:
    runs-on: ubuntu-latest
    outputs:
      lambda_function_name: ${{ github.event.inputs.lambda_function_name }}
      prev_lambda_function_version: ${{ github.event.inputs.prev_lambda_function_version }}
      lambda_function_version: ${{ github.event.inputs.lambda_function_version }}
      weighted_traffic_percentage: ${{ github.event.inputs.weighted_traffic_percentage }}
      environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Echo Selected Color
        run: echo "You have selected  ${{ github.event.inputs.environment }} !"

  execute-dev-environment:
    needs: selections
    runs-on: ubuntu-latest
    steps:
      - name: Execute Steps dev environment
        run: echo "Executing steps ${{ needs.selection.outputs.environment}}"
        
