name: Blue-Green Deployment

on:
  workflow_dispatch:
    inputs:
      lambda_function_name:
        description: "Lambda function to apply the deployment strategy to"
        type: string
        required: true
      prev_lambda_function_version:
        description: "Previous Lambda function version to update the alias"
        required: true
        type: string
      lambda_function_version:
        description: "Lambda function version to update the alias"
        required: true
        type: string
      weighted_traffic_percentage:
        description: "The weighted traffic amount (in decimal) to be updated with the deployment strategy"
        type: string
        required: true
      environment:
        description: "Environment to run deploy against"
        type: environment
        required: true
permissions:
  id-token: write
  contents: read
env:
  NODE_VERSION: "20.x"
jobs:
  selections:
    runs-on: ubuntu-latest
    outputs:
      lambda_function_name: ${{ github.event.inputs.lambda_function_name }}
      prev_lambda_function_version: ${{ github.event.inputs.prev_lambda_function_version }}
      lambda_function_version: ${{ github.event.inputs.lambda_function_version }}
      weighted_traffic_percentage: ${{ github.event.inputs.weighted_traffic_percentage }}
      environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Echo Inputs
        run: |
          echo "Inputs  lambda_function_name ${{ github.event.inputs.lambda_function_name }} \
          prev_lambda_function_version ${{ github.event.inputs.prev_lambda_function_version }} \
          lambda_function_version ${{ github.event.inputs.lambda_function_version }} \
          weighted_traffic_percentage ${{ github.event.inputs.weighted_traffic_percentage }} \"
          environment ${{ github.event.inputs.environment }} "

  dev-deployment:
    name: Blue-Green Deploy to Dev
    needs: selections
    runs-on: ubuntu-latest
    environment: dev
    if: ${{ needs.selections.outputs.environment == 'dev' }} && github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/fix/')
    steps:
      - uses: actions/checkout@v2
      - name: "Deploy"
        uses: ./.github/action/action_blue_green
        with:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
          LAMBDA_FUNCTION_NAME: ${{ inputs.lambda_function_name }}
          PREV_LAMBDA_FUNCTION_VERSION: ${{ inputs.prev_lambda_function_version }}
          LAMBDA_FUNCTION_VERSION: ${{ inputs.lambda_function_version }}
          ALIAS_NAME: dev
          WEIGHTED_TRAFFIC_PCT: ${{ inputs.weighted_traffic_percentage }}
          NODE_VERSION: ${{ env.NODE_VERSION }}
          ENVIRONMENT: dev
  stage-deployment:
    name: Blue-Green Deploy to Stage
    needs: selections
    runs-on: ubuntu-latest
    environment: stage
    if: ${{ needs.selections.outputs.environment == 'stage' }} && github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v2
      - name: "Deploy"
        uses: ./.github/action/action_blue_green
        with:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
          LAMBDA_FUNCTION_NAME: ${{ inputs.lambda_function_name }}
          PREV_LAMBDA_FUNCTION_VERSION: ${{ inputs.prev_lambda_function_version }}
          LAMBDA_FUNCTION_VERSION: ${{ inputs.lambda_function_version }}
          ALIAS_NAME: stage
          WEIGHTED_TRAFFIC_PCT: ${{ inputs.weighted_traffic_percentage }}
          NODE_VERSION: ${{ env.NODE_VERSION }}
          ENVIRONMENT: stage
  prod-deployment:
    name: Blue-Green Deploy to Prod
    needs: selections
    runs-on: ubuntu-latest
    environment: prod
    if: ${{ needs.selections.outputs.environment == 'prod' }} && github.ref == 'refs/heads/production'
    steps:
      - uses: actions/checkout@v2
      - name: "Deploy"
        uses: ./.github/action/action_blue_green
        with:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
          LAMBDA_FUNCTION_NAME: ${{ inputs.lambda_function_name }}
          PREV_LAMBDA_FUNCTION_VERSION: ${{ inputs.prev_lambda_function_version }}
          LAMBDA_FUNCTION_VERSION: ${{ inputs.lambda_function_version }}
          ALIAS_NAME: prod
          WEIGHTED_TRAFFIC_PCT: ${{ inputs.weighted_traffic_percentage }}
          NODE_VERSION: ${{ env.NODE_VERSION }}
          ENVIRONMENT: prod


        
