name: Blue-Green Deployment

on:
  push:
    branches:
      - development
      - staging
      - production
  workflow_dispatch:
    inputs:
      lambda_function_name:
        description: "Lambda function to apply the deployment strategy to"
        type: string
        required: true
      prev_lambda_function_version:
        description: "Previous Lambda function version to update the alias"
        required: true
        type: string
      lambda_function_version:
        description: "Lambda function version to update the alias"
        required: true
        type: string
      weighted_traffic_percentage:
        description: "The weighted traffic amount (in decimal) to be updated with the deployment strategy"
        required: true
        type: string
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true
permissions:
  id-token: write
  contents: read
env:
  NODE_VERSION: "20.x"
jobs:
  dev-deployment:
    name: Blue-Green Deploy to Dev
    runs-on: ubuntu-latest
    environment: dev
    if: github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/fix/')
    steps:
      - uses: actions/checkout@v2
      - name: "Deploy"
        uses: ./.github/action/action_blue_green
        with:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
          LAMBDA_FUNCTION_NAME: ${{ inputs.lambda_function_name }}
          PREV_LAMBDA_FUNCTION_VERSION: ${{ inputs.prev_lambda_function_version }}
          LAMBDA_FUNCTION_VERSION: ${{ inputs.lambda_function_version }}
          ALIAS_NAME: dev
          WEIGHTED_TRAFFIC_PCT: ${{ inputs.weighted_traffic_percentage }}
          NODE_VERSION: ${{ env.NODE_VERSION }}
          ENVIRONMENT: dev
  stage-deployment:
    name: Blue-Green Deploy to Stage
    runs-on: ubuntu-latest
    environment: stage
    if: github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v2
      - name: "Deploy"
        uses: ./.github/action/action_blue_green
        with:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
          LAMBDA_FUNCTION_NAME: ${{ inputs.lambda_function_name }}
          PREV_LAMBDA_FUNCTION_VERSION: ${{ inputs.prev_lambda_function_version }}
          LAMBDA_FUNCTION_VERSION: ${{ inputs.lambda_function_version }}
          ALIAS_NAME: stage
          WEIGHTED_TRAFFIC_PCT: ${{ inputs.weighted_traffic_percentage }}
          NODE_VERSION: ${{ env.NODE_VERSION }}
          ENVIRONMENT: stage
  prod-deployment:
    name: Blue-Green Deploy to Prod
    runs-on: ubuntu-latest
    environment: prod
    if: github.ref == 'refs/heads/production'
    steps:
      - uses: actions/checkout@v2
      - name: "Deploy"
        uses: ./.github/action/action_blue_green
        with:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
          LAMBDA_FUNCTION_NAME: ${{ inputs.lambda_function_name }}
          PREV_LAMBDA_FUNCTION_VERSION: ${{ inputs.prev_lambda_function_version }}
          LAMBDA_FUNCTION_VERSION: ${{ inputs.lambda_function_version }}
          ALIAS_NAME: prod
          WEIGHTED_TRAFFIC_PCT: ${{ inputs.weighted_traffic_percentage }}
          NODE_VERSION: ${{ env.NODE_VERSION }}
          ENVIRONMENT: prod
