name: Blue-Green Deployment

on:
  workflow_dispatch:
    inputs:
      which_infrastructure:
        description: "Select the infrastructure to which this deploy will be sent. A: Bottlers B: Sellers"
        required: true
        default: "A"
        type: choice
        options:
          - A
          - B
      become_active:
        description: "Should infrastructure selected above become active?"
        required: true
        type: boolean
        default: false
      environment_b:
        description: "Environment to run deploy against"
        required: true
        default: "A"
        type: choice
        options:
          - dev
          - stage
          - prod
permissions:
  id-token: write
  contents: read
env:
  NODE_VERSION: "20.x"
jobs:
  selections:
    runs-on: ubuntu-latest
    outputs:
      which_infrastructure: ${{ github.event.inputs.which_infrastructure }}
      become_active: ${{ github.event.inputs.become_active }}
      environment: ${{ github.event.inputs.environment_b }}
    steps:
      - name: Echo Inputs
        run: |
          echo "Inputs  which_infrastructure ${{ github.event.inputs.which_infrastructure }} \
          echo become_active ${{ github.event.inputs.become_active }} \
          echo environment ${{ github.event.inputs.environment_b }} "

  dev-deployment:
    name: Blue-Green Deploy to Dev infrastructure
    needs: selections
    runs-on: ubuntu-latest
    environment: dev
    if: ${{ inputs.environment_b == 'dev'}} && (github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/fix/'))
    steps:
      - name: Echo Inputs
        id: echo-inputs2
        shell: bash
        run: |
          echo "Inputs  which_infrastructure ${{ github.event.inputs.which_infrastructure }} \
          become_active ${{ github.event.inputs.become_active }} \
          environment ${{ github.event.inputs.environment_b }} "

      - uses: actions/checkout@v2
      - name: "Deploy"
        uses: ./.github/action/action_blue_green
        with:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
          WHICH_INFRASTRUCTURE: ${{ inputs.which_infrastructure }}
          BECOME_ACTIVE: ${{ inputs.become_active }}
          SSM_PARAM_INFRASTRUCTURE: ${{ vars.SSM_PARAM_DEV_INFRA }}
          SELLERS_DOMAIN_NAME: ${{ vars.DOMAIN_NAME_DEV }}
          BASE_PATH: ${{ vars.SELLERS_BASE_PATH }}
          NODE_VERSION: ${{ env.NODE_VERSION }}
          ENVIRONMENT: dev

  stage-deployment:
    name: Blue-Green Deploy to Stage infrastructure
    needs: selections
    runs-on: ubuntu-latest
    environment: stage
    if: ${{ inputs.environment_b == 'stage' }} && (github.ref == 'refs/heads/staging' || startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/fix/'))
    steps:
      - name: Echo Inputs
        id: echo-inputs3
        shell: bash
        run: |
          echo "Inputs  which_infrastructure ${{ github.event.inputs.which_infrastructure }} \
          become_active ${{ github.event.inputs.become_active }} \
          environment ${{ github.event.inputs.environment_b }} "
          
      - uses: actions/checkout@v2
      - name: "Deploy"
        uses: ./.github/action/action_blue_green
        with:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
          WHICH_INFRASTRUCTURE: ${{ inputs.which_infrastructure }}
          BECOME_ACTIVE: ${{ inputs.become_active }}
          SSM_PARAM_INFRASTRUCTURE: ${{ vars.SSM_PARAM_STAGE_INFRA }}
          SELLERS_DOMAIN_NAME: ${{ vars.DOMAIN_NAME_STAGE }}
          BASE_PATH: ${{ vars.SELLERS_BASE_PATH }}
          NODE_VERSION: ${{ env.NODE_VERSION }}
          ENVIRONMENT: stage

  prod-deployment:
    name: Blue-Green Deploy to Prod infrastructure
    needs: selections
    runs-on: ubuntu-latest
    environment: prod
    if:  ${{ inputs.environment_b == 'prod' }} && ( github.ref == 'refs/heads/production' || startsWith(github.ref, 'refs/heads/hotfix/') )
    steps:
      - name: Echo Inputs
        id: echo-inputs4
        shell: bash
        run: |
          echo "Inputs  which_infrastructure ${{ github.event.inputs.which_infrastructure }} \
          become_active ${{ github.event.inputs.become_active }} \
          environment ${{ github.event.inputs.environment_b }} "
          
      - uses: actions/checkout@v2
      - name: "Deploy"
        uses: ./.github/action/action_blue_green
        with:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
          WHICH_INFRASTRUCTURE: ${{ inputs.which_infrastructure }}
          BECOME_ACTIVE: ${{ inputs.become_active }}
          SSM_PARAM_INFRASTRUCTURE: ${{ vars.SSM_PARAM_PROD_INFRA }}
          SELLERS_DOMAIN_NAME: ${{ vars.DOMAIN_NAME_STAGE }}
          BASE_PATH: ${{ vars.SELLERS_BASE_PATH }}
          NODE_VERSION: ${{ env.NODE_VERSION }}
          ENVIRONMENT: prod
