name: Deploy app
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      which_environment:
        type: choice
        description: Which environment do you want to deploy? A or B (Active - Inactive)
        default: A
        options:
          - A
          - B
        required: true
      stage:
        type: choice
        description: Which app do you want to deploy
        options:
          - stage
          - dev
        required: true
      region:
        description: Region to deploy
        required: true
        default: 'us-east-1'
permissions:
  id-token: write
  contents: read
env:
  STAGE: ${{ github.event.inputs.stage || 'stage' }}
  AWS_REGION: ${{ github.event.inputs.region || 'us-east-2' }}
  # it could be passed as parameter
  APP_NAME: app1
  APP_NAME_B: app2
jobs:
  deployment:
    name: Deploy app-integration ${{ github.event.inputs.stage }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Step 1
        run: sls config credentials --provider aws --key ${{ env.AWS_ACCESS_KEY_ID }} --secret ${{ env.AWS_SECRET_ACCESS_KEY }}
      - name: Step 2 Deploy ${{ format('{0}_{1}', env.APP_NAME , env.STAGE) }} to ${{ env.AWS_REGION }}
        if: github.event.inputs.stage == 'stage' && github.event.inputs.which_environment == 'A'
        run: |
          echo "You selected stage stage and environment A"
      - name: Deploy ${{ format('{0}_{1}', env.APP_NAME_B , env.STAGE) }} to ${{ env.AWS_REGION }}
        if: github.event.inputs.stage == 'stage' && github.event.inputs.which_environment == 'B'
        run: |
          echo "You selected stage stage and environment B"
